name: llvm-aio
version: git
grade: stable
confinement: strict
base: core22
summary: LLVM All-In-One toolchain
description: LLVM All-In-One toolchain

architectures:
  - build-on: [amd64]
    build-for: [amd64]
  - build-on: [arm64]
    build-for: [arm64]

slots:
  llvm-libraries:
    interface: content
    content: llvm-libraries
    source:
      read:
        - $SNAP/usr/lib
  llvm-headers:
    interface: content
    content: llvm-headers
    source:
      read:
        - $SNAP/usr/include

apps:
  clang:
    environment:
      LD_LIBRARY_PATH: ${SNAP}/lib:${SNAP}/usr/lib:${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}
    command: usr/bin/clang
    plugs: [ home, removable-media ]
  clang-plus-plus:
    environment:
      LD_LIBRARY_PATH: ${SNAP}/lib:${SNAP}/usr/lib:${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}
    command: clangpp
    plugs: [ home, removable-media ]
  ar:
    environment:
      LD_LIBRARY_PATH: ${SNAP}/lib:${SNAP}/usr/lib:${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}
    command: usr/bin/llvm-ar
    plugs: [ home, removable-media ]
  as:
    environment:
      LD_LIBRARY_PATH: ${SNAP}/lib:${SNAP}/usr/lib:${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}
    command: usr/bin/llvm-as
    plugs: [ home, removable-media ]
  ld-lld:
    environment:
      LD_LIBRARY_PATH: ${SNAP}/lib:${SNAP}/usr/lib:${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}
    command: usr/bin/ld.lld
    plugs: [ home, removable-media ]
  ld64-lld:
    environment:
      LD_LIBRARY_PATH: ${SNAP}/lib:${SNAP}/usr/lib:${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}
    command: usr/bin/ld64.lld
    plugs: [ home, removable-media ]
  wasm-ld:
    environment:
      LD_LIBRARY_PATH: ${SNAP}/lib:${SNAP}/usr/lib:${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}
    command: usr/bin/wasm-ld
    plugs: [ home, removable-media ]
  llc:
    environment:
      LD_LIBRARY_PATH: ${SNAP}/lib:${SNAP}/usr/lib:${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}
    command: usr/bin/llc
    plugs: [ home, removable-media ]
  lld:
    environment:
      LD_LIBRARY_PATH: ${SNAP}/lib:${SNAP}/usr/lib:${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}
    command: usr/bin/lld
    plugs: [ home, removable-media ]
  lldb:
    environment:
      LD_LIBRARY_PATH: ${SNAP}/lib:${SNAP}/usr/lib:${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}
    command: usr/bin/lldb
    plugs: [ home, removable-media, network, system-trace ]
  readobj:
    environment:
      LD_LIBRARY_PATH: ${SNAP}/lib:${SNAP}/usr/lib:${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}
    command: usr/bin/llvm-readobj
    plugs: [ home, removable-media ]
  objdump:
    environment:
      LD_LIBRARY_PATH: ${SNAP}/lib:${SNAP}/usr/lib:${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}
    command: usr/bin/llvm-objdump
    plugs: [ home, removable-media ]
  strip:
    environment:
      LD_LIBRARY_PATH: ${SNAP}/lib:${SNAP}/usr/lib:${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}
    command: usr/bin/llvm-strip
    plugs: [ home, removable-media ]
  llvm-config:
    environment:
      LD_LIBRARY_PATH: ${SNAP}/lib:${SNAP}/usr/lib:${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}
    command: usr/bin/llvm-config
    plugs: [ home, removable-media ]

parts:
  llvm:
    plugin: cmake
    source: https://github.com/llvm/llvm-project.git
    source-tag: llvmorg-17.0.6
    source-subdir: llvm
    cmake-parameters:
      - -GNinja
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DLLVM_TARGETS_TO_BUILD="all"
      - -DLLVM_ENABLE_PROJECTS='clang;lld;lldb'
      - -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi;libunwind"
      - -DLLVM_ENABLE_EH=ON
      - -DLLVM_ENABLE_RTTI=ON
      - -DLLVM_LINK_LLVM_DYLIB=ON
      - -DLLDB_INCLUDE_TESTS=OFF
      - -DCMAKE_BUILD_TYPE=Release
    build-packages:
      - cmake
      - ninja-build
      - build-essential
      - dpkg-dev
      - libssl-dev
      - libcrypt-dev
      - curl
      - clang
      - python3
    stage-packages:
      - libatomic1
      - libc6-dev
  wrappers:
    plugin: dump
    source: wrappers/
